# Generated by Django 6.0.1 on 2026-01-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akademk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
